DROP TABLE IF EXISTS city;
DROP TABLE IF EXISTS demographics;
DROP TABLE IF EXISTS education;
DROP TABLE IF EXISTS family;
DROP TABLE IF EXISTS health_data;
DROP TABLE IF EXISTS nation;
DROP TABLE IF EXISTS state;